import { initializeTrailEffect } from "./effects/Trail/trail.js";
import { initializeRippleEffect } from "./effects/Ripple/ripple.js";
import { initializeSpiralEffect } from "./effects/Spiral/spiral.js";
import { initializePixelationEffect } from "./effects/Pixels/pixels.js";
import { initializeInterlaceEffect } from "./effects/Interlace/interlace.js";
import { initializeWeldEffect } from "./effects/Weld/weld.js";
import { initializeStreamEffect } from "./effects/Stream/stream.js";
import { initializeShatterEffect } from "./effects/Shatter/shatter.js";
import { initializeIlluminateEffect } from "./effects/Illuminate/illuminate.js";
import { initializeWaterEffect } from "./effects/Water/water.js";

const trailButton = document.querySelector(".trail-button");
const rippleButton = document.querySelector(".ripple-button");
const spiralButton = document.querySelector(".spiral-button");
const pixelsButton = document.querySelector(".pixels-button");
const interlaceButton = document.querySelector(".interlace-button");
const weldButton = document.querySelector(".weld-button");
const streamButton = document.querySelector(".stream-button");
const shatterButton = document.querySelector(".shatter-button");
const illuminateButton = document.querySelector(".illuminate-button");
const waterButton = document.querySelector(".water-button");

initializeTrailEffect(trailButton);
initializeRippleEffect(rippleButton);
initializeSpiralEffect(spiralButton);
initializePixelationEffect(pixelsButton);
initializeInterlaceEffect(interlaceButton);
initializeWeldEffect(weldButton);
initializeStreamEffect(streamButton);
initializeShatterEffect(shatterButton);
initializeIlluminateEffect(illuminateButton);
initializeWaterEffect(waterButton);
